name: lilanhdo_workflows
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  get_cli: ^1.8.1
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  dio: ^5.0.3
  flutter_asset_generator: ^1.0.2
  google_fonts: ^4.0.3
  device_preview: ^0.1.4-beta
  flutter_launcher_icons: ^0.12.0
  intl: ^0.18.0
  test: ^1.22.0
  package_info_plus: ^1.4.2
  logger: ^1.3.0
  flutter_dotenv: ^5.0.2
  get_storage: ^2.1.1
  flutter_native_splash: ^2.2.19
  carousel_slider: ^4.2.1
  gradient_borders: ^1.0.0
  flutter_slidable: ^3.0.0
  dropdown_button2: ^2.1.0
  flutterfire_cli: ^0.2.7
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  permission_handler: ^10.2.0
  sentry: ^7.5.0
  firebase_messaging: ^14.4.1
  firebase_in_app_messaging: ^0.7.1+1
  flutter_screenutil: ^5.7.0
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
