// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93cEqBxbKodOktsEgw4OjdKR490Im0Mc',
    appId: '1:686651634286:web:ced1fdcbb9bfbc673d2c7f',
    messagingSenderId: '686651634286',
    projectId: 'lilanhdo-workflows',
    authDomain: 'lilanhdo-workflows.firebaseapp.com',
    databaseURL: 'https://lilanhdo-workflows-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lilanhdo-workflows.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA42_0ntje_NLgCHh47rS0HNt5ZEgjW2lk',
    appId: '1:686651634286:android:0f273bac247478d83d2c7f',
    messagingSenderId: '686651634286',
    projectId: 'lilanhdo-workflows',
    databaseURL: 'https://lilanhdo-workflows-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lilanhdo-workflows.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrykX_O6DvgnJbT4PFNbCIgGG0bwujnoE',
    appId: '1:686651634286:ios:561399fb0df394213d2c7f',
    messagingSenderId: '686651634286',
    projectId: 'lilanhdo-workflows',
    databaseURL: 'https://lilanhdo-workflows-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lilanhdo-workflows.appspot.com',
    iosClientId: '686651634286-917t1ktt1ninb3d8i22u58nu6sjboffr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lilanhdoWorkflows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrykX_O6DvgnJbT4PFNbCIgGG0bwujnoE',
    appId: '1:686651634286:ios:561399fb0df394213d2c7f',
    messagingSenderId: '686651634286',
    projectId: 'lilanhdo-workflows',
    databaseURL: 'https://lilanhdo-workflows-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lilanhdo-workflows.appspot.com',
    iosClientId: '686651634286-917t1ktt1ninb3d8i22u58nu6sjboffr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lilanhdoWorkflows',
  );
}
